apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
  namespace: starttech
data:
  PORT: "8080"
  DB_NAME: "starttech"
  ENABLE_CACHE: "false"
  REDIS_ADDR: ""
  REDIS_PASSWORD: ""
  ALLOWED_ORIGINS: "http://localhost:5173,http://localhost:3000"
